#!/bin/bash
#this script display informations about subdomains

# Function to display information about a subdomain
display_subdomain_info() {

    # Extracting information using awk
    record_type=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION" | awk 'NR==2 {print $4}')
    destination=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION" | awk 'NR==2 {print $5}')

    echo "The subdomain $2 is a $record_type record and points to $destination"
}

# Main script
if [ "$#" -eq 2 ]; then
    # Display information for the specified subdomain
    display_subdomain_info "$1" "$2"
else
    # Display information for default subdomains
    display_subdomain_info "$1" "www"
    display_subdomain_info "$1" "lb-01"
    display_subdomain_info "$1" "web-01"
    display_subdomain_info "$1" "web-02"
fi
