#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Set ownership and permissions
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# Create a simple "Hello World" index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Reload UFW to apply changes
sudo ufw reload
