#!/usr/bin/env bash
# This script configures Nginx to perform a 301 redirect for /redirect_me

# Configure Nginx for redirection
sudo sed -i '/server_name localhost;/a \\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
