#!/usr/bin/env bash
# Configures an Ubuntu machine with Nginx

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a simple HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure Nginx with redirection, error page, and custom header
echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        add_header X-Served-By $HOSTNAME;
        location / {
                try_files $uri $uri/ =404;
        }
}' > /etc/nginx/sites-available/default
service nginx restart
