#!/usr/bin/env bash
# This script install your load balancer

sudo apt-get update -y
sudo apt-get install -y haproxy
sudo echo 'frontend web
    bind 0.0.0.0:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 54.237.91.205:80 check
    server web-02 35.174.205.66:80 check' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
