#!/usr/bin/env bash
# This file is made to manage_my_process

MY_PROCESS_PID=/var/run/my_process.pid

start() {
        ./manage_my_process &
        sudo touch $MY_PROCESS_PID
	sudo bash -c "echo $$ > $MY_PROCESS_PID"
        echo "manage_my_process started"
}

stop() {
    if [ -e "$MY_PROCESS_PID" ]; then
        sudo pkill -f "./manage_my_process"
        sudo rm "$MY_PROCESS_PID"
        echo "manage_my_process stopped"
    fi
}

restart() { 
    $0 stop >& /dev/null
    $0 start >& /dev/null
    echo "manage_my_process restarted"
}

if [ "$1" == "start" ]; then
    start
elif [ "$1" == "stop" ]; then
    stop
elif [ "$1" == "restart" ]; then
    restart
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
