#!/usr/bin/env bash
# This script lists files in the current directory, displaying only the part of the name after the first dash

for file in *; do
name_after_dash="$(echo "$file" | cut -d '-' -f 2-)"
        echo "$name_after_dash"
done;
